zones:
  combre_valtin:
    nom: "Combe Valtin"
    cadastre: "data/cadastre/POI_Combe_Valtin.shp"
    roi: [6.98, 48.10, 7.03, 48.13]
    years: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
